### ISSUE TITLE
"NSFW" inconsistently marked on YouTube video links

### ISSUE THREAD

**Issue by mpenguin** [TotallyNotRobots/CloudBot#135]
When pasting a YouTube link into chat (#casualconversation), gonzobot provides the title, runtime, author, etc. At times, video links are marked as NSFW (in red text) by gonzobot, although this NSFW branding does not exist on the YouTube page.

Sometimes, posting the video multiple times does not trigger the NSFW marking on repeated postings. 

A few possibilities for this issue:
- The NSFW branding is provided by YouTube, but is being inconsistently interpreted by gonzobot
- The NSFW branding is applied by gonzobot (based on what?) and being applied inconsistently.

This does not appear to be related to Channel or User Modes.

**Comment by linuxdaemon** [comment]
Currently the bot looks for the `contentRating` field in the api response, but doesn't check the values. I'll change it to use https://developers.google.com/youtube/v3/docs/videos#contentDetails.contentRating.ytRating
