### ISSUE TITLE
crontab 

### ISSUE THREAD

**Issue by sacredland** [TotallyNotRobots/CloudBot#204]
I have a crontab job to start the bot:
@reboot /usr/bin/python3 CloudBot/cloudbot >/dev/null 2>&1 2> /home/cloud/cloudbot.log

It was working well, but since few day I got that error into the cron log:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "CloudBot/cloudbot/__main__.py", line 8, in <module>
    from cloudbot.bot import CloudBot
ModuleNotFoundError: No module named 'cloudbot'

**Comment by A-UNDERSCORE-D** [comment]
Cloudbot is started as a module. So you will need to run `python3 -m cloudbot` from the installation directory

**Comment by sacredland** [comment]
@A-UNDERSCORE-D I know all that. My issue is related to the crontab. Read.. it was working, like that, very well. No needs to stay in console. Now it doesnt work.

**Comment by A-UNDERSCORE-D** [comment]
You're not starting cloudbot correctly and any magic we may have done to make that work has been removed.

**Comment by sacredland** [comment]
@A-UNDERSCORE-D it's why i just did a bash script instead to do it, witch work a1.
