### ISSUE TITLE
.imdb not showing votes for some shows/movies (?)

### ISSUE THREAD

**Issue by bornyhitch** [TotallyNotRobots/CloudBot#24]
05:40:41 <@usr> .imdb The Mandalorian
05:40:49 <@cli> (usr) The Mandalorian (2019) (): The travails of a lone gunfighter in the outer reaches of the galaxy, far from the authority of the New Republic. 1h. **_unrated/10 with 0 votes._** http://www.imdb.com/title/tt8111088
05:40:57 <@usr> https://www.imdb.com/title/tt8111088/

**Comment by linuxdaemon** [comment]
@flotwig I think this is a problem with your API

**Comment by flotwig** [comment]
@linuxdaemon thanks, i will look into it. opened an issue on the `imdb-scraper` repo for tracking: flotwig/imdb-scraper#5

people seem to be really into the IMDb plugin lately :sweat_smile:

**Comment by flotwig** [comment]
i have the votes fixed, there are still some issues with the plugin not showing all genres:

```
<gonzobot> (flotwig) The Mandalorian (2019) (): The travails of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic. 30min. 9.1/10 with 34448 votes. http://www.imdb.com/title/tt8111088
```

**Comment by linuxdaemon** [comment]
@flotwig any more fixes needed for this?

**Comment by flotwig** [comment]
@linuxdaemon it still doesn't show Genre, but i am tracking it in my own repo, it's not a gonzobot issue
