### ISSUE TITLE
aop's don't have permissions where channel ops do

### ISSUE THREAD

**Issue by patrickfixedit** [TotallyNotRobots/CloudBot#537]
Running my bot on an irc server with aops and channel ops, channel ops have permissions to do things such as starthunt but aops get permission denied notices.

**Comment by linuxdaemon** [comment]
Hey @patrickfixedit can you send me a copy of the 005 lines received by the bot? it is supposed to parse those to determine channel op prefixes

**Comment by patrickfixedit** [comment]
hey it is working now. Something must have changed between then and now.
