### ISSUE TITLE
Wikipedia API no longer returns page snippets

### ISSUE THREAD

**Issue by linuxdaemon** [TotallyNotRobots/CloudBot#69]
This leads to 
```
18:06:31 <@gonzobot> Error occurred in wikipedia.wiki
18:06:31 <@gonzobot> AttributeError: 'NoneType' object has no attribute 'text'
```
when searching for anything

**Comment by znuxor** [comment]
Probably caused by this https://phabricator.wikimedia.org/T241437

**Comment by znuxor** [comment]
Seems to be the case unfortunately.

A fix would be to do a second request using the following URL:

https://en.wikipedia.org/w/api.php?action=query&prop=extracts&explaintext=true&exintro=true&exsectionformat=plain&exchars=143&format=xml&titles=Pizza

(transform exchars and titles into variable parameters as necessary. Content is not guaranteed to contain exactly exchars characters)

More information can be found at:
https://www.mediawiki.org/wiki/Extension:TextExtracts#API
